export function sum(a: number, b: number): number {
    return a + b;
}
export function substract(a: number, b: number): number {
    return a - b;
}
export function multiply(a: number, b: number): number {
    return a * b;
}
export function divide(a: number, b: number): number {
    return a / b;
}



/**
 * This function calculates the factorial of a number using recursion.
 * Note: This code was generated by AI for testing purposes.
 */
export function factorial(n: number): number {
    if (n < 0) {
        throw new Error("Factorial is not defined for negative numbers.");
    }
    return n === 0 ? 1 : n * factorial(n - 1);
}

// ...existing code...

/**
 * This function calculates the nth Fibonacci number using recursion.
 * Note: This code was generated by AI for testing purposes.
 */
export function fibonacci(n: number): number {
    if (n < 0) {
        throw new Error("Fibonacci is not defined for negative numbers.");
    }
    return n <= 1 ? n : fibonacci(n - 1) + fibonacci(n - 2);
}

/**
 * This function checks if a number is prime.
 * Note: This code was generated by AI for testing purposes.
 */
export function isPrime(num: number): boolean {
    if (num <= 1) return false;
    for (let i = 2; i <= Math.sqrt(num); i++) {
        if (num % i === 0) return false;
    }
    return true;
}

/**
 * This function generates a random integer between two values, inclusive.
 * Note: This code was generated by AI for testing purposes.
 */
export function getRandomInt(min: number, max: number): number {
    if (min > max) {
        throw new Error("Min value cannot be greater than max value.");
    }
    return Math.floor(Math.random() * (max - min + 1)) + min;
}

/**
 * This function reverses a string.
 * Note: This code was generated by AI for testing purposes.
 */
export function reverseString(str: string): string {
    return str.split('').reverse().join('');
}

/**
 * This function calculates the greatest common divisor (GCD) of two numbers.
 * Note: This code was generated by AI for testing purposes.
 */
export function gcd(a: number, b: number): number {
    return b === 0 ? a : gcd(b, a % b);
}

/**
 * This function calculates the least common multiple (LCM) of two numbers.
 * Note: This code was generated by AI for testing purposes.
 */
export function lcm(a: number, b: number): number {
    return Math.abs(a * b) / gcd(a, b);
}

/**
 * This function converts a string to title case.
 * Note: This code was generated by AI for testing purposes.
 */
export function toTitleCase(str: string): string {
    return str
        .toLowerCase()
        .split(' ')
        .map(word => word.charAt(0).toUpperCase() + word.slice(1))
        .join(' ');
}

/**
 * This function flattens a nested array.
 * Note: This code was generated by AI for testing purposes.
 */
export function flattenArray(arr: any[]): any[] {
    return arr.reduce((flat, item) => {
        return flat.concat(Array.isArray(item) ? flattenArray(item) : item);
    }, []);
}

/**
 * This function calculates the power of a number using recursion.
 * Note: This code was generated by AI for testing purposes.
 */
export function power(base: number, exponent: number): number {
    if (exponent < 0) {
        throw new Error("Exponent must be a non-negative integer.");
    }
    return exponent === 0 ? 1 : base * power(base, exponent - 1);
}

/**
 * This function checks if a string is a palindrome.
 * Note: This code was generated by AI for testing purposes.
 */
export function isPalindrome(str: string): boolean {
    const cleaned = str.replace(/[^a-zA-Z0-9]/g, '').toLowerCase();
    return cleaned === cleaned.split('').reverse().join('');
}

/**
 * This function calculates the sum of an array of numbers.
 * Note: This code was generated by AI for testing purposes.
 */
export function sumArray(numbers: number[]): number {
    return numbers.reduce((sum, num) => sum + num, 0);
}

/**
 * This function finds the maximum value in an array of numbers.
 * Note: This code was generated by AI for testing purposes.
 */
export function findMax(numbers: number[]): number {
    return Math.max(...numbers);
}

/**
 * This function finds the minimum value in an array of numbers.
 * Note: This code was generated by AI for testing purposes.
 */
export function findMin(numbers: number[]): number {
    return Math.min(...numbers);
}

/**
 * This function calculates the average of an array of numbers.
 * Note: This code was generated by AI for testing purposes.
 */
export function calculateAverage(numbers: number[]): number {
    if (numbers.length === 0) {
        throw new Error("Cannot calculate the average of an empty array.");
    }
    return sumArray(numbers) / numbers.length;
}